apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: cattle-neuvector-system
spec:
  replacePathRegex:
    regex: /fedmanaged:443\/*(.*)
    replacement: /$1
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nv-ingressroute
  namespace: cattle-neuvector-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`nv.rajesh-kumar.in`)
    kind: Rule
    services:
    - name: neuvector-service-webui
      port: 8443
      scheme: https
  - match: Host(`nv.rajesh-kumar.in`) && PathPrefix(`/fedmanaged`)
    kind: Rule
    services:
      - name: neuvector-svc-controller-fed-master
        passHostHeader: true
        port: 11443
        scheme: https
    middlewares:
      - name: stripprefix
  tls:
    secretName: rancher-tls-cert

