apiVersion: v1
data:
  objstore.yml: |
    type: "S3"
    config: 
      bucket: "{{ .BUCKET_NAME }}"
      endpoint: "s3.ap-south-1.amazonaws.com"
      region: "ap-south-1"
      aws_sdk_auth: false
      access_key: "{{ .ACCESS_KEY }}"
      insecure: false
      signature_version2: false
      secret_key: "{{ .SECRET_KEY }}"
kind: ConfigMap
metadata:
  name: thanos-objconfig
  namespace: monitoring
